---
- name: Configure remote Server
  hosts: all 
  become: yes
  tasks:
    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: true

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker's GPG key
      get_url:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Set correct Docker repository
      set_fact:
        docker_repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"

    - name: Add Docker repository to APT sources
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: "{{ docker_repo }}"
        mode: '0644'

    - name: Update apt cache
      apt:
        update_cache: yes
      register: apt_update
      until: apt_update is succeeded
      retries: 5
      delay: 2

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Ensure Docker service is running and enabled
      service:
        name: docker
        state: started
        enabled: yes
