---
- name: Deploy MongoDB + Mongo-Express stack from git
  hosts: mongodb
  become: yes
  vars:
    repo_url: "https://github.com/mihamieat/mongo-plus-express-compose.git"
    branch: "master"
    project_dir: "/opt/mongodb_stack"

  tasks:
    - name: Ensure project directory exists
      ansible.builtin.file:
        path: "{{ project_dir }}"
        state: directory
        mode: "0755"

    - name: Stop and clean up any existing stack
      ansible.builtin.command: >
        docker compose -f "{{ project_dir }}/docker-compose.yml" down --volumes --remove-orphans
      args:
        chdir: "{{ project_dir }}"
      ignore_errors: yes
      register: cleanup_result
      changed_when: false
      tags: deploy

    - name: Clone/update repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dir }}"
        version: "{{ branch }}"
        force: yes
        update: yes
      tags: deploy

    - name: Set secure permissions for compose files
      ansible.builtin.file:
        path: "{{ project_dir }}"
        mode: "0750"
        recurse: yes

    - name: Deploy MongoDB stack
      ansible.builtin.command: >
        docker compose -f "{{ project_dir }}/docker-compose.yml" up -d --pull always
      args:
        chdir: "{{ project_dir }}"
      environment:
        DB_ROOT_USERNAME: "{{ db_root_user }}"
        DB_ROOT_PASSWORD: "{{ db_root_pass }}"
        DB_UI_AUTH_USERNAME: "{{ db_ui_user }}"
        DB_UI_AUTH_PASSWORD: "{{ db_ui_pass }}"
      tags: deploy

    - name: Wait for MongoDB to be ready
      ansible.builtin.wait_for:
        host: localhost
        port: 27017
        state: present

    - name: Create user
      ansible.builtin.command: >
        sudo docker exec -it mongodb mongosh \
        --username={{ db_root_user }}
        --password={{ db_root_pass }} \
        --authenticationDatabase admin \
        --eval '
        use {{ database_client }};
        db.createCollection("user");
        db.users.insertOne({username: "{{ db_root_user }}", password: {{ db_root_pass }});
        '
