- name: Deploy Gpac-API Docker App
  hosts: backend
  become: yes
  tasks:
    - name: Pull Docker Image
      community.docker.docker_image:
        name: mihamieat/gpac-api
        source: pull
        tag: develop
        force_source: true

    - name: Stop and remove existing container
      ansible.builtin.command: |
        docker rm -f gpac-api
      ignore_errors: true

    - name: Run Docker container
      ansible.builtin.docker_container:
        name: gpac-api
        image: mihamieat/gpac-api:develop
        ports:
          - 80:80
        env:
          DATABASE_CONNECTION_STRING: "{{ database_connection_string }}"
          DATABASE_CLIENT: "{{ database_client }}"
        restart_policy: always
